name: Pull Request

on:
  pull_request:
    branches:
      - main
      - github-actions 

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: lint check
        run: npx stylelint "**/*.scss"

 
 